group: dependencies
depends_on:
  - forge
steps:
  # dependencies
  - label: ":tapioca: build: pip-compile dependencies"
    key: pip_compile_dependencies
    tags: always
    instance_type: small
    commands:
      # uncomment the following line to update the pinned versions of pip dependencies
      # to the latest versions; otherwise, the pinned versions will be re-used as much
      # as possible
      # - rm ./python/requirements_compiled.txt
      - cp ./python/requirements_compiled.txt requirements_compiled_backup.txt
      - ./ci/ci.sh compile_pip_dependencies
      - cp -f ./python/requirements_compiled.txt /artifact-mount/
      - diff ./python/requirements_compiled.txt requirements_compiled_backup.txt || (echo "requirements_compiled.txt is not up to date. Please download it from Artifacts tab and git push the changes." && exit 1)
    job_env: oss-ci-base_test-py3.11
    depends_on: oss-ci-base_test-multipy

  - label: ":tapioca: build: raydepsets: compile LLM dependencies"
    key: raydepsets_compile_llm_dependencies
    tags: always
    instance_type: small
    command: ./ci/test_compile_llm_requirements.sh
    job_env: oss-ci-base_test-py3.11
    depends_on: oss-ci-base_test-multipy

  - label: ":tapioca: build: raydepsets: compile ray img dependencies"
    key: raydepsets_compile_rayimg_dependencies
    tags: always
    instance_type: small
    commands:
      - bazel run //ci/raydepsets:raydepsets -- build ci/raydepsets/rayimg.depsets.yaml
      -
    job_env: oss-ci-base_test-py3.11
    depends_on: oss-ci-base_test-multipy

  - label: ":tapioca: build & test placeholder wheel {{matrix}}"
    key: raydepsets_compile_rayimg_dependencies
    tags: always
    instance_type: medium
    commands:
      # validate minimal installation
      - python ./ci/env/check_minimal_install.py --expected-python-version {{matrix}}
      - python -m pip install --upgrade pip
      # build placeholder wheel
      - export RAY_DEBUG_BUILD=deps-only
      - mkdir -p .whl
      - pip wheel python/ --no-deps -w .whl/ --use-pep517
      - ls -a .whl
      # compile rayimg dependencies
      - echo "ray[all]==100.0.0-dev" > python/ray-requirement.txt
      - bazel run //ci/raydepsets:raydepsets -- build ci/raydepsets/rayimg.depsets.yaml
      - rm python/ray-requirement.txt
    depends_on:
      - minbuild-core
    job_env: minbuild-core-py{{matrix}}
    matrix:
      - "3.9"
      - "3.10"
      - "3.11"
      - "3.12"
