name: "ray-py$PYTHON_VERSION-cpu-base"
froms: ["ubuntu:22.04"]
dockerfile: docker/base-deps/Dockerfile
srcs:
  - python/requirements_compiled.txt
build_args:
  - PYTHON_VERSION
  - BASE_IMAGE=ubuntu:22.04
  - RAY_IMAGE_EXTRA
tags:
  - cr.ray.io/rayproject/ray-py$PYTHON_VERSION-cpu-base
